[package]
authors = ["The Rust Project Developers"]
name = "libtest"
version = "0.0.0"
edition = "2018"

[lib]
name = "libtest"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
libc = { version = "0.2", default-features = false }
term = "0.6.0"
getopts = "0.2.21"